import React, { useState } from 'react';
import './AISummaryModal.css';

const AISummaryModal = ({ messages, metadata, onClose }) => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateSummary = async () => {
    setLoading(true);
    setError('');

    try {
      const response = await fetch('http://localhost:8000/api/chat/generate-summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: messages,
          metadata: metadata
        })
      });

      const data = await response.json();

      if (data.success) {
        setSummary(data.summary);
      } else {
        setError(data.error || 'Failed to generate summary');
      }
    } catch (err) {
      setError('Failed to connect to the server. Make sure backend is running.');
      console.error('Summary generation error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!summary) return;

    const summaryText = formatSummaryForCopy(summary);
    navigator.clipboard.writeText(summaryText).then(() => {
      alert('✅ Summary copied to clipboard!');
    });
  };

  const handleDownload = () => {
    if (!summary) return;

    const summaryText = formatSummaryForCopy(summary);
    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `case_summary_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const formatSummaryForCopy = (summary) => {
    if (typeof summary.summary_text === 'string') {
      return `LEGAL CASE SUMMARY
Generated: ${new Date(summary.generated_at).toLocaleString()}
Law Type: ${summary.metadata?.law_type || 'Not specified'}
Jurisdiction: ${summary.metadata?.jurisdiction || 'Not specified'}

${summary.summary_text}

---
CONVERSATION STATISTICS
Total Messages: ${summary.conversation_stats?.total_messages || 0}
Client Messages: ${summary.conversation_stats?.user_messages || 0}
Assistant Responses: ${summary.conversation_stats?.assistant_messages || 0}
Duration: ${summary.conversation_stats?.duration || 'N/A'}

---
DISCLAIMER: This is an AI-generated summary of general legal information provided during the conversation. 
It is NOT legal advice and should not be relied upon as such. For advice specific to your situation, 
consult with a licensed lawyer in your jurisdiction.

Generated by LEGID Legal Assistant - ${new Date().toLocaleDateString()}`;
    }
    
    return JSON.stringify(summary, null, 2);
  };

  const parseSummaryText = (text) => {
    if (!text) return null;

    // Split by numbered sections
    const sections = text.split(/\n(?=\d+\.\s+[A-Z])/);
    
    return sections.map((section, index) => {
      const lines = section.trim().split('\n');
      const title = lines[0];
      const content = lines.slice(1).join('\n');
      
      return (
        <div key={index} className="summary-section">
          <h3>{title}</h3>
          <div className="summary-content">
            {content.split('\n').map((line, i) => (
              <p key={i}>{line}</p>
            ))}
          </div>
        </div>
      );
    });
  };

  return (
    <div className="ai-summary-overlay">
      <div className="ai-summary-modal">
        <div className="summary-header">
          <div className="header-title">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
              <polyline points="14 2 14 8 20 8"></polyline>
              <line x1="16" y1="13" x2="8" y2="13"></line>
              <line x1="16" y1="17" x2="8" y2="17"></line>
              <polyline points="10 9 9 9 8 9"></polyline>
            </svg>
            <h2>AI Case Summary</h2>
          </div>
          <button className="close-button" onClick={onClose}>✕</button>
        </div>

        <div className="summary-content-area">
          {!summary && !loading && (
            <div className="summary-intro">
              <div className="intro-icon">
                <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
              </div>
              <h3>Generate AI-Powered Case Summary</h3>
              <p>
                Our AI will analyze your entire conversation and generate a comprehensive legal case summary including:
              </p>
              <ul className="features-list">
                <li>📋 Client situation analysis</li>
                <li>⚖️ Legal issues identified</li>
                <li>💡 Advice provided</li>
                <li>📊 Key facts and evidence</li>
                <li>✅ Recommended next steps</li>
                <li>⚠️ Risk assessment</li>
                <li>👨‍⚖️ Professional recommendations</li>
              </ul>
              <div className="conversation-info">
                <span>📊 {messages.length} messages to analyze</span>
                {metadata?.law_category && (
                  <span>⚖️ {metadata.law_category}</span>
                )}
                {metadata?.jurisdiction && (
                  <span>📍 {metadata.jurisdiction}</span>
                )}
              </div>
              <button 
                className="generate-btn" 
                onClick={generateSummary}
                disabled={loading}
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path>
                  <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
                  <line x1="12" y1="22.08" x2="12" y2="12"></line>
                </svg>
                Generate AI Summary
              </button>
            </div>
          )}

          {loading && (
            <div className="summary-loading">
              <div className="loading-spinner">
                <div className="spinner"></div>
              </div>
              <h3>Analyzing Conversation...</h3>
              <p>AI is reviewing {messages.length} messages and generating your case summary</p>
              <div className="loading-steps">
                <div className="step">✓ Reading conversation</div>
                <div className="step active">⟳ Analyzing legal issues</div>
                <div className="step">○ Generating summary</div>
              </div>
            </div>
          )}

          {error && (
            <div className="summary-error">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="8" x2="12" y2="12"></line>
                <line x1="12" y1="16" x2="12.01" y2="16"></line>
              </svg>
              <h3>Error Generating Summary</h3>
              <p>{error}</p>
              <button className="retry-btn" onClick={generateSummary}>
                Try Again
              </button>
            </div>
          )}

          {summary && (
            <div className="summary-result">
              <div className="result-header">
                <div className="header-info">
                  <h3>✅ Case Summary Generated</h3>
                  <div className="summary-meta">
                    <span>📅 {new Date(summary.generated_at).toLocaleString()}</span>
                    <span>⚖️ {summary.metadata?.law_type || 'General Law'}</span>
                    <span>📍 {summary.metadata?.jurisdiction || 'Not specified'}</span>
                  </div>
                </div>
                <div className="header-actions">
                  <button className="action-btn" onClick={handleCopy} title="Copy to clipboard">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                    </svg>
                    Copy
                  </button>
                  <button className="action-btn" onClick={handleDownload} title="Download as text file">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                      <polyline points="7 10 12 15 17 10"></polyline>
                      <line x1="12" y1="15" x2="12" y2="3"></line>
                    </svg>
                    Download
                  </button>
                  <button className="action-btn" onClick={generateSummary} title="Regenerate summary">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polyline points="23 4 23 10 17 10"></polyline>
                      <polyline points="1 20 1 14 7 14"></polyline>
                      <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>
                    </svg>
                    Regenerate
                  </button>
                </div>
              </div>

              <div className="summary-stats">
                <div className="stat-card">
                  <div className="stat-value">{summary.conversation_stats?.total_messages || 0}</div>
                  <div className="stat-label">Total Messages</div>
                </div>
                <div className="stat-card">
                  <div className="stat-value">{summary.conversation_stats?.user_messages || 0}</div>
                  <div className="stat-label">Client Questions</div>
                </div>
                <div className="stat-card">
                  <div className="stat-value">{summary.conversation_stats?.assistant_messages || 0}</div>
                  <div className="stat-label">Responses</div>
                </div>
                <div className="stat-card">
                  <div className="stat-value">{summary.conversation_stats?.duration || 'N/A'}</div>
                  <div className="stat-label">Duration</div>
                </div>
              </div>

              <div className="summary-text">
                {typeof summary.summary_text === 'string' ? (
                  <div className="formatted-summary">
                    {parseSummaryText(summary.summary_text)}
                  </div>
                ) : (
                  <pre>{JSON.stringify(summary, null, 2)}</pre>
                )}
              </div>

              <div className="summary-disclaimer">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
                  <line x1="12" y1="9" x2="12" y2="13"></line>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
                <div>
                  <strong>Important Disclaimer:</strong> This is an AI-generated summary of general legal information 
                  provided during the conversation. It is NOT legal advice and should not be relied upon as such. 
                  For advice specific to your situation, consult with a licensed lawyer in your jurisdiction.
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AISummaryModal;
